name: de_novo
channels:
  - conda-forge
  - rdkit
  - openbabel
  - pytorch
  - anaconda
  - defaults
dependencies:
  - matplotlib=3.0.3
  - nbformat=4.4.0
  - numpy=1.16.2
  - numpy-base=1.16.2
  - openbabel=2.4.1
  - pandas=0.24.2
  - pillow=5.4.1
  - python=3.7.4
  - pytorch=1.0.0
  - torchvision=0.2.1
  - rdkit=2018.09.2.0
  - scikit-learn=0.20.2
  - scipy=1.2.1
  - seaborn=0.9.0
  - pip=19.1.1
  - jupyter
  - pip:
    - torchsummary==1.5.1
